# Generated by Django 5.0.7 on 2024-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_imageslider_remove_cart_list_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_list',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription End Date'),
        ),
        migrations.AddField(
            model_name='item_list',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Start Date'),
        ),
    ]
