# Generated by Django 5.0.7 on 2024-09-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_item_list_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_list',
            name='base_price_id',
        ),
    ]
