# Generated by Django 5.0.7 on 2024-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_item_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_list',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
