# Generated by Django 5.0.7 on 2024-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_item_list_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
