# Generated by Django 5.0.7 on 2024-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('غياب', 'غياب')], default='حضور', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
