# Generated by Django 5.0.7 on 2024-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_alter_attendance_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subscription_type',
            field=models.CharField(choices=[('Term', 'Term Subscription'), ('50_days', '50 Days Subscription'), ('35_days', '35 Days Subscription')], default='Term', max_length=20),
        ),
    ]
