# Generated by Django 5.0.7 on 2024-09-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_attendance_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subscription_type',
        ),
    ]
