# Generated by Django 5.0.7 on 2024-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_remove_attendance_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='arrival_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='Arrival Status'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='departure_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='Departure Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
