# Generated by Django 5.0.7 on 2024-09-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_remove_attendance_arrival_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف')], default='غياب', max_length=10),
        ),
    ]
