# Generated by Django 5.0.7 on 2024-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_remove_attendance_departure_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
