# Generated by Django 5.0.7 on 2024-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_attendance_departure_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='حالة الحضور'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departure_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='حالة الانصراف'),
        ),
    ]
