# Generated by Django 5.0.7 on 2024-09-07 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_alter_attendance_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('غياب', 'غياب'), ('حضور', 'حضور')], default='غياب', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departure_status',
            field=models.CharField(choices=[('غياب', 'غياب'), ('انصراف', 'انصراف')], default='غياب', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
