# Generated by Django 5.0.7 on 2024-10-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='departure_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='حالة الانصراف'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('انصراف', 'انصراف'), ('غياب', 'غياب')], default='غياب', max_length=10, verbose_name='حالة الحضور'),
        ),
        migrations.AlterField(
            model_name='item_list',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
