# Generated by Django 5.0.7 on 2024-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_attendance_departure_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_list',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
