# Generated by Django 5.0.7 on 2024-10-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_alter_item_list_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_list',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
